### PR TITLE
Added support for locale on DatePicker dialog component

### PR DESCRIPTION
**Pull request by aabilio**
Updated components, docs and spec.

### CODE REVIEW

**Comment by aabilio** [comment]
This is not a PR to address #623, just a simple way to provide strings to DatePicker to show months and days in other languages (with some predefined languages loaded).

**Comment by javivelasco** [comment]
Beautiful work! I think this is very useful and does not create any breaking changes so happy to merge! Thanks 💃 !

**Comment by sanfilippopablo** [comment]
This is great. When is this going to be on NPM?

**Comment by aabilio** [comment]
I just realize that action buttons ('Cancel' and 'OK') need to be translated too. I was thinking on inserting it in locale prop too (pro: easy api for Date Picker component) but I think that inserting new properties like okButtonLabel, cancelButtonLabel, dismissButtonLabel... could make sense too (pro: standarization of action buttons). What do you think?

**Comment by javivelasco** [comment]
I think they should come from props as you mentioned. In fact, all internationalization in a library such as react-toolbox should be based on that. Anyway there are not a lot of components with text so it should be easy.

**Comment by sanfilippopablo** [comment]
While the props option sounds more technically correct, I think that the
labels being attributes on the locale object is more useful, because the
default locale with the string locale prop is simple option that covers 95%
of the use cases. Besides, it would still allow customization through the
object locale prop.

**Comment by javivelasco** [comment]
Yeah maybe. It also would be a cleaner api. More options on this would be great

**Pull request merged**
