### PR TITLE
Update README.md for PostCSS instead of SASS

### PR DESCRIPTION
**Pull request by alexhisen**

### CODE REVIEW

**Comment by javivelasco** [comment]
Great work! Thank you!! :)

**Comment by alexhisen** [comment]
Thanks. In my opinion, the project is ready for a 2.0 (non-beta) release.

**Comment by javivelasco** [comment]
I think maybe it makes sense to release 2.0 as stable and to call the refactor to 3.0

**Comment by supirman** [comment]
If I use `create-react-app`, do I need to include postcss too instead of using react-toolbox-themr guide?

**Comment by javivelasco** [comment]
Not really! You can use react-toolbox-themr to generate your custom stylesheets and forget about configuration.

**Comment by olegstepura** [comment]
@alexhisen react-toolbox-example is adapted for react-toolbox 2.0, but isn't updated and contains some basiс setup. Your statement `It hasn't yet been updated for 2.0!` is wrong

**Pull request merged**
