### PR TITLE
Range option added to Slider

### PR DESCRIPTION
**Pull request by nocon**
I've added a Range option to Toolbox Slider:

screen shot 2015-12-12 at 18 07 16

It's not polished/refactored yet, but I could use a review before I finish it. Thanks!

### CODE REVIEW

**Comment by javivelasco** [comment]
I think this is useful but I don't know if it's documented in Material Design spec.
Could you make Travis pass and check if they are officially documented?

**Comment by javivelasco** [comment]
Ping here!

**Comment by nocon** [comment]
Range slider is not documented in Material Design spec. Do you still want me to make it pass Travis checks, or should this be shelved until it becomes part of the spec?

**Comment by javivelasco** [comment]
I would rather keep it for now if it's not part of the spec. It would be nice to develop it in another package so you can include useful components modifications that are not part of the spec optionally

**Comment by scrawfor** [comment]
I have a need for something like this. Did it, or something like it ever get added to another package anywhere?

**Comment by javivelasco** [comment]
I will try to make a demo on how can you compose your own with Slider subcomponents but I need some time to make it work!

**Comment by KeizerDev** [comment]
Any update?

**Comment by tonymaibox** [comment]
Would like to know if there's an update also! Many thanks in advance 😄

**Pull request closed without merging**
