### PR TITLE
+ Pager control, actually it is not defined at matereal design but de…

### PR DESCRIPTION
**Pull request by MaximKomlev**
Pager control, actually it is not defined at matereal design but definitely it is helpful to have.

the control is based on react-toolbox controls and corresponds to matereal design. It is highly customisable and it follows default style patterns of react-toolbox components. actually what differentiate the control from others similar that it has always const set of buttons and the set depends on two properties: number of total pages (latsPage) and number of visible pages at block. e.g.
[<][1][...][4][5][6][...][8][>] or [<][1][2][3][4][5][...][8][>] or [<][1][...][4][5][6][7][8][>] where block size is 3. it gives smooth user experience. A layouting is based on flex but easily can be rewritten using inline-block at custom theme.

example is added to specs.

### CODE REVIEW

**Comment by javivelasco** [comment]
Great work! The code looks very good and respects React Toolbox patterns, lovely ❤️ 

There is an open discussion #626 about components that are out of the spec though. We agreed that maybe the best option is to create a separate repository for this complementary components and I agree that would be probably the best to separate official vs opinionated components.

Also, a PostCSS release is coming so maybe you'd like to update. I think it could be cool to add a section in the docs mentioning complementary components. This would keep this component in a separated repository with a dependency to react-toolbox. When we put together some components with can open a "react toolbox addons package".

Not sure yet anyway but in any case I'd prefer to merge to PostCSS directly.
What do you think??

**Comment by javivelasco** [comment]
Also check out the linter errors!

**Comment by MaximKomlev** [comment]
Hi Javi,
What you are saying it makes sense, i think so. I didn't find any related repository or project therefore I've tried to publish my experiments such way. Definitely, it would be great to have repository where people could share his experience around react-toolbox to make it more powerful. I found react-toolbox very useful and highly customizable, I like it.

**Comment by neekey** [comment]
@MaximKomlev good work, need this component too. Any plan about how to publish your component?

**Comment by javivelasco** [comment]
@MaximKomlev thank you so much. If you want, you can publish your component and open a PR with a modification in the Readme or Docs with a new section detailing the link to your component. Something like `Complementary components` or `Components out of the spec`... something like that.

If the component is not included in this same repository cause it's more opinionated, we still can include a link to your repo until we set up a complements repository. What do you think??

**Comment by MaximKomlev** [comment]
@javivelasco I will do this way thank you.

**Comment by javivelasco** [comment]
Thank you for an awesome work @MaximKomlev ! Please don't forget that PR to the react toolbox docs/readme

**Comment by MaximKomlev** [comment]
@javivelasco @neekey  Hey, guys I started project for additions which I guess could be helpful to have but which are not included at react-toolbox components library.
https://github.com/MaximKomlev/react-toolbox-additions
I would so appreciate if you could give me your review before publishing.

**Comment by neekey** [comment]
@MaximKomlev Nice work, I think I will take a look tonight : )

**Comment by neekey** [comment]
@MaximKomlev I haven't gone through all your implementation details only read about your API, and I think it's not very clear:

- `prevButtonContent` and `nextButtonContent`: Since their prop types are `string` I think renaming them like `nextButtonLabel` will be easier to understand
- `lastPage`: I was quite confused by this one at first, after going through your code I then realized it is actually `totalPage`, which is a more conventional name.
- `rangeLeftButtonContent`: First of all, it's quite a new feature to me that you make the "range" clickable, but I'm not sure if this is necessary. Secondly, it's very hard to understand what is "rangeLeftButton" at the first glimpse, and still, may consider replacing `content` to `label`.
- `***ButtonTypes`: I noticed the prop type is `object` but the name is `*Types`, quite confused me. I suggest instead of giving the control of all separated buttons, you can just provide a whole component level theme prop to set predefined button style set like:

```js
<Pager raised  ... />
<Pager flat  ... />
``` 
Since I don't think anyone will set left button to raised and right button to flat.

Good work 👍 by the way.

**Comment by MaximKomlev** [comment]
Thank you, for your review, I updated interface according to your comments. actually left and right buttons for ranges and arrow have one style, just can be populated by different content. I attached screen of how it can be styled.

I did clickable the ranges button such I think it more useful.
pager_screenshot

**Comment by neekey** [comment]
@MaximKomlev the screenshot looks good 👍

**Comment by MaximKomlev** [comment]
Hey, I published first version of rt addons, for now, I added two components Pager and FilePicker, if it will be interesting to somebody I have a couple more ideas about components.
https://www.npmjs.com/package/react-toolbox-additions

**Comment by javivelasco** [comment]
@MaximKomlev please PR a README update detailing the project link. Other people can find it useful

**Comment by MaximKomlev** [comment]
I will... on this weekend, thank you.

**Comment by MaximKomlev** [comment]
@javivelasco , Hi, I would like to confirm..., so it should be something like:
##Extensions
....

Before
## License
is it ok?
Thank you.

**Comment by javivelasco** [comment]
Sure, yeah!

**Pull request closed without merging**
