### PR TITLE
Dropdown with icon

### PR DESCRIPTION
**Pull request by jyoona**
Added the ability to add icon to dropdown fields

### CODE REVIEW

**Comment by hamzapurra** [comment]
I don't think that is needed. It already works for Dropdown. Dropdown passes it via others to Input.

**Comment by jyoona** [comment]
Do you mean template? Or is icon actually already a thing?
If it's for template we need to add an icon to each dropdown element, which is different from what I'm trying to implement.

**Comment by javivelasco** [comment]
@hamzapurra is right. [Here](https://github.com/react-toolbox/react-toolbox/blob/master/components/dropdown/Dropdown.js#L133) additional props are passed down to `Input` and it accepts an Icon. So it should work already

**Comment by javivelasco** [comment]
I'm going to close to avoid noise. In case you can't make it work, please reopen.
Thanks for your pr!

**Pull request closed without merging**
