### PR TITLE
Remove global styles

### PR DESCRIPTION
**Pull request by okonet**
** This is WIP! Please don't merge! **

An attempt to remove global styles from react-toolbox.

### CODE REVIEW

**Comment by javivelasco** [comment]
Great! This is definitively needed

**Comment by javivelasco** [comment]
How is it going? If would be cool to release it with PostCSS. I plan to merge ASAP, I can keep working on this if you want

**Comment by okonet** [comment]
@javivelasco I'll definitively need your help with some parts. Let's chat next week some time?

**Comment by javivelasco** [comment]
Of course! Just ping me @ discord :)

**Pull request closed without merging**
