### PR TITLE
Issue 1459: Replace onClick handler in Dropdown component to onMouseDown

### PR DESCRIPTION
**Pull request by torpeyp**
Fixes https://github.com/react-toolbox/react-toolbox/issues/1459

### CODE REVIEW

**Comment by joelzimmer** [comment]
Can anyone take a look at this?

**Comment by dibinp** [comment]
This would be helpful for me too. Can someone take a look?

**Comment by talibnelson** [comment]
Ditto

**Comment by josephahn** [comment]
please

**Comment by mbilokonsky** [comment]
yup

**Comment by jvivs** [comment]
@javivelasco Any chance you can take a look at this? We're currently maintaining an internal fork because of this bug and would love to rejoin the flock :)

**Comment by javivelasco** [comment]
I'm back!

**Comment by joejsx** [comment]
This change seems to have broken the latest dev branch Dropdown component. Tested on Firefox and Chrome, it needs two clicks in order to hide the Dropdown and touching/dragging across a list item will cause it to select.

**Pull request merged**
