### PR TITLE
Add `valueLink` to Input

### PR DESCRIPTION
**Pull request by LestaD**
https://facebook.github.io/react/docs/two-way-binding-helpers.html

### CODE REVIEW

**Comment by oliviertassinari** [comment]
`valueLink` is going to be removed from the react core. I wouldn't go into this direction.

**Comment by javivelasco** [comment]
Agree with @oliviertassinari Two way binding helpers sound like an antipattern in react from my POV.
Do you have a specific scenario where you are using them and they can't be removed? Removing `valueLink` from core means a lot

**Comment by LestaD** [comment]
@oliviertassinari 
> ReactLink is just a thin wrapper and convention around the onChange/setState() pattern. It doesn't fundamentally change how data flows in your React application.

Where you read about removing `valueLink` from react core? proof?

**Comment by oliviertassinari** [comment]
@LestaD  https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/ReactDOMInput.js#L98

**Comment by LestaD** [comment]
@oliviertassinari oh!

**Pull request closed without merging**
