### PR TITLE
Fixed Autocomplete such that it does not error when provided with a value prop that does not exist in the source prop.

### PR DESCRIPTION
**Pull request by therealparmesh**
Fixed Autocomplete such that it does not error when provided with a value prop that does not exist in the source prop.

### CODE REVIEW

**Comment by therealparmesh** [comment]
This problem only occurs for Autocompletes where the provided multiple prop is false.

**Comment by javivelasco** [comment]
I've merged the PR manually to `dev` which is the branch we use for development. `master` is intended to keep the source for the last official release version and PRs should be directed to there.

Thanks for the PR! 💃

**Comment by zweiler** [comment]
I see you've merged already, but is it possible to merge this [PR](https://github.com/react-toolbox/react-toolbox/pull/692) instead? Instead of setting the value to undefined, it preserves the value text.

**Comment by therealparmesh** [comment]
@javivelasco Thank you for merging a fix in for this issue; It really helps in a Redux-driven application. Also, I'll be sure to direct any future contributions to the `dev` branch.
@zweiler Thank you for providing a clean fix!

**Pull request closed without merging**
