### PR TITLE
Fix TimePicker dismiss issue

### PR DESCRIPTION
**Pull request by merraysy**
Clicking on the `TimePicker`'s `overlay` or tapping `ESC` to dismiss the dialog wasn't working, I've added the missing fallback props as you guys did in the `DatePicker` [Here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/date_picker/DatePicker.js#L149).

### CODE REVIEW

**Comment by rubenmoya** [comment]
Why are there changes to the `Tabs` component?

**Comment by merraysy** [comment]
@rubenmoya It's my bad. only the second commit matters here.

**Comment by rubenmoya** [comment]
Hi! Could you revert that commit so we can merge this please?

**Comment by rubenmoya** [comment]
Thank you! :)

**Pull request merged**
