### PR TITLE
Use consistent data attributes

### PR DESCRIPTION
**Pull request by fredguest**
data-toolbox should be data-react-toolbox to be consistent with the rest of the components.

### CODE REVIEW

**Comment by javivelasco** [comment]
Agree with you. Maybe in this PR we can add other data attributes that are missing for some components before merging. What do you think?

**Comment by fredguest** [comment]
ya good call, i'll add to this PR.

**Comment by fredguest** [comment]
should be good to go unless you see something missing, or have a reason to prefer data-role over data-react-toolbox.

**Comment by javivelasco** [comment]
Nice! I see it ok :) thanks!

**Pull request merged**
