### PR TITLE
Issue #59 - Babel 6 Upgrade

### PR DESCRIPTION
**Pull request by Bartekus**
As per issue: .babelrc incompatible with Babel 6 #59

Bebel 6 has been integrated, Stage-0 has been added, React and Webpack have also been updated.
In addition webpack configuration files have been slightly tweaked and adjusted to babel 6 changes. 

Currently the Autocomplete.jsx file is disabled due to bug in babel https://phabricator.babeljs.io/T6712

Aside from toolbox-loader, and excluding highlight & sinon, everything else has been updated.

With all test passing this pull is now complete.

### CODE REVIEW

**Comment by javivelasco** [comment]
This is great. The only thing that I don't like is the need to disabled `Autocomplete` component. I think it should be fixed before merging so we can have the `dev` branch working nicely and ready to merge at any point. What do you think? It's going to take too long, is there anything that can be changed to avoid the bug?

Thanks @Bartekus great work!

**Comment by Bartekus** [comment]
I'm looking into fixing Autocomplete but after taking two days off I'm only getting back into it now so a little bit more time is needed before I come up with a solution. Thank you for patience and stay tuned!

**Comment by carloscuatin** [comment]
what is the problem in autocomplete ??

**Comment by Bartekus** [comment]
The problem is this:
```
SyntaxError: components/autocomplete/Autocomplete.jsx: "suggestions2" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)
```
and it relates to this: https://phabricator.babeljs.io/T6712

**Comment by Bartekus** [comment]
Unfortunately at the moment I'm lacking skills to fix this problem properly and hacking it into passing a test won't guarantee artifact-free operation hence I'd like to sway away from that option. 
I will monitor the open tickets for the solution on the babel side and implement the solution as soon as one is found.

**Comment by javivelasco** [comment]
Great, don't worry! :)

**Comment by vicentedealencar** [comment]
looking at Autocomplete.jsx I see
```
suggestions () {
  const suggestions = new Map();
```

maybe this is the source of error related to `constant inside class method of same name`? https://phabricator.babeljs.io/T6712

maybe changing this const name fix it

I wasn't able to build it on windows, so I couldn't try it

**Comment by langri-sha** [comment]
Keeping the books in order: this also fixes #230.

**Comment by javivelasco** [comment]
Fixed and merged! Thanks everybody! :D

**Pull request merged**
