### PR TITLE
Created DynamicAutocomplete field.

### PR DESCRIPTION
**Pull request by dhamilton91**
Hey guys,

This is a new Dynamic Autocomplete component. 
It is used to dynamically populate the suggestions so that a service can be called to return results.

David

### CODE REVIEW

**Comment by javivelasco** [comment]
Hi! What do you mean by Dynamic? You can always change the source prop and the autocomplete will change as well

**Comment by javivelasco** [comment]
Also, this is pretty much duplicating code :(

**Comment by dhamilton91** [comment]
You can update the source dynamically but you cant easily use the value from the input to use as a service call parameter. Also the current autocomplete field does some extra filtering which is unnecessary in this situation.

**Comment by kagux** [comment]
I think a dry approach would be allowing to pass optional search function as prop.

**Pull request closed without merging**
