### PR TITLE
Created required behaviour for input

### PR DESCRIPTION
**Pull request by KerenChandran**
References #376 

I added a span tag containing an asterisk in the label for input to help identify required fields. I also created a separate required variable in scss in case if the user wants to use a different color. As of now, the color is set to match the error text. If an error is present, the required style is currently set to overwrite the error style for the asterisk.

### CODE REVIEW

**Comment by javivelasco** [comment]
Apparently there are some conflicts! May you solve them to merge? I think it's a good improvement.
Thanks for your prs @KerenChandran !!

**Comment by KerenChandran** [comment]
Alright I'll solve the conflicts around 9PM EST today (March 17). Also no
problem, I really want to contribute to the repo cause I'm new to web dev
and love the work you're doing!

**Comment by KerenChandran** [comment]
I should also mention this fixes #376

**Comment by javivelasco** [comment]
Thank you so much @KerenChandran !
Sorry I was out for some days!

**Pull request merged**
