### PR TITLE
Adding Event to be passed for Radio Group for handleClick function similar as other components #1544

### PR DESCRIPTION
**Pull request by yuliaHope**
Implements https://github.com/react-toolbox/react-toolbox/pull/1544 in `master` branch.

### CODE REVIEW

**Comment by rubenmoya** [comment]
Thank you for your contribution! :)

**Comment by yuliaHope** [comment]
@rubenmoya Could you update sources in npm repository, please? Now they're not relevant.

**Comment by rubenmoya** [comment]
I have a pending talk with Javi about that. I'll release this changes as soon as I can.

**Comment by yuliaHope** [comment]
Many thanks!

**Pull request merged**
