### PR TITLE
ListItem legend may be a node as well

### PR DESCRIPTION
**Pull request by olegstepura**
Currently it works, but produces a warning by react typechecking

### CODE REVIEW

**Comment by olegstepura** [comment]
@javivelasco please review this, I have this pain of seeng lots of warnings from React typechiecking but everuthing else works. Thanks!

**Comment by olegstepura** [comment]
Anything stops from merging this?

**Comment by javivelasco** [comment]
Thanks!

**Comment by javivelasco** [comment]
Sorry, personal issues are pushing me away from dedicating time to the project. That's the reason for this stupid inactivity

**Comment by olegstepura** [comment]
Hopefully you will solve personal issues to allow yourself do what you love =)

**Pull request merged**
