### PR TITLE
[Table] enhancements

### PR DESCRIPTION
**Pull request by Kosta-Github**
- allow usage of `react` components in table cells (header and rows): https://github.com/react-toolbox/react-toolbox/issues/268
- allow changing table header titles (via `title` prop in `model`): https://github.com/react-toolbox/react-toolbox/issues/296
- allow specifying `onChange` handler per column (via `model`) in order to make only certain columns editable instead of the whole table

Sample usage can be seen in the update `Table` test file.

### CODE REVIEW

**Comment by javivelasco** [comment]
Let me check it this afternoon :) Great work

**Comment by epilgrim** [comment]
Nice one! Allowing to pass ReactComponents for fields and headers makes total sense.
As we go that way, wouldn't' make sense also deprecate the magic around auto-editable fields?

now, we can pass custom components. Why not let those components to be bound to onChange events, or onclick, or whatever. The table is supposed to display in a tabl-y way. All the other behaviour should be on each passed component. We can pass now any Input, Autocomplete, select, etc.

Anyways, if you don't want to deprecate that behavior (for BC), I don't think that adding the onChange by column is necessary anymore, for the same points stated above.

What do you think?

**Comment by Kosta-Github** [comment]
I agree with @epilgrim that the cell content should be responsible for doing the proper `onChange` handling.

But I wanted to make as little changes as possible to achieve all 3 goals listed above without introducing breaking changes to existing code.

**Comment by javivelasco** [comment]
Very useful, thanks!

**Pull request merged**
