### PR TITLE
[chore] several maintenance upgrades

### PR DESCRIPTION
**Pull request by that1matt**
I have made some significant changes to react-toolbox, to bring it up to date as it was hard to use in some of my new projects without getting errors, or issues with compiling. This PR does a lot of maintenance cleanup, and brings the package up to date on several libraries in an effort to hopefully allow for easier changes in the future.

I am not sure if this library is maintained anymore, but if it is and you need help, I would be glad to help keep the package up to date, as I really like using css modules when building sites. I am currently using this forked version, with a forked version of react-css-themr. Just reach out and let me know if you would like help maintaining this package and react-css-themr as well.

### Thoughts/Discussions
I would also like to rename all `.css` files to `.module.css`  as this seems to be the naming convention for all css modules libraries.

## Broken
Currently the `docs/` folder doesn't build or run, all its dependencies need to be upgraded, and changes to webpack. I have not done that yet, and wanted to have it part of a separate PR, as this one is already large.

## Breaking Changes
- Upgrade babel@6 to babel@7
- Changed `prepublish` to `prepare` in `package.json` to remove npm error.

## Changes
- **Added** dependencies
`postcss-calc`
`postcss-normalize`
`husky`
`eslint-plugin-jest`
`react-hot-loader`
`extract-css-chunks-webpack-plugin`

- **Removed** dependencies
`extract-css-text-plugin`
`normalize.css`
`sinon`
`caniuse-db`
`babel-plugin-react-transform`
`postcss-nesting`
`react-transform-catch-errors`
`react-transform-hmr`
 `redbox-react`

Update `.gitignore`
Remove `jest.polyfill.js` (no longer needed with latest jest)`.
Extract jest config from `package.json` to `jest.config.json`.
Replace `normalize.css` with `postcss-normalize` and changed spec import from `normalize.css` to `@csstools/normalize.css`
Update `gulpfile.js` to use new `gulp` library.
Add `husky.config.js` for using with `lint-staged`.
Add `lint-staged.config.js` to run `pre-commit` commands
Changed `.babelrc` to `babel.config.js` part of babel@7 upgrade
Changed `.stylelintrc` to `stylelint.config.js`
Changed Icon Button Alignment `background-color` from `red` to `grey` as it seemed to indicate that the button was broken or an issue.

## Fixes
Fix broken `color()` css function to `color-mod()` part of new `postcss-preset-env` change, missed from [PR#1862](https://github.com/react-toolbox/react-toolbox/pull/1862)
Added `postcss-calc` to actually convert nested css `calc()` functions. Required for `postcss-preset-env` as it is not included as it was with `postcss-cssnext`,  missed from [PR#1862](https://github.com/react-toolbox/react-toolbox/pull/1862)
Fix broken avatar links in spec list items.
Fix broken stylelint key missing quotes.
Fixed majority of stylelint issues in components. 
Fixed majority of eslint issues in components.

### CODE REVIEW

**Comment by rubenmoya** [comment]
Hello @that1matt, thank you for all this effort, I really appreaciate it, I tried to take care of the library but it seems like I don't as muchfree time as I thought, so any help is really welcome.

I've seen that you added a `package-lock.json`, I'm ok with the change, but could you remove the `yarn.lock`?

Also I've seen that you made some changes to the stylelint config and Travis is complaining about it, do you mind fixing it?

I'll merge this as soon as is green

**Comment by that1matt** [comment]
Hey @rubenmoya , no worries. I understand how that goes. I appreciate all the work you and the other maintainers have done.

I will continue to do what I can through PRs, and I hope we can get some newer betas out with all the changes that the community has been putting in.

Let me know if you see any issues, and as I have noted the docs page is not working. I was thinking of using something like next.js or gatsby.js to build the docs website in the future for easier maintainability.

**Comment by rubenmoya** [comment]
Yeah, we could use Gatsby, and also start it in a different repo, or setup lerna and do it here, but separated form the actual project.

Another thing I was thinking was using something like Storybook or Styleguidst for development, since right now we're using a big file with all the components and that's a pain in the ass to work with and debug problems, what do you think?

**Comment by that1matt** [comment]
I currently use storybook for all the internal UI components we build. I really like it, and they are just about to release v4, which adds some really sought after features.

I think we should still have a spec sheet, but use it more for automated testing to compare snapshots on new builds, such as a pixel by pixel basis.

I think creating a new repo for docs and using gatsby/next is a great idea, and it would reduce the main core package for react-toolbox.

I also wonder, if there is a way @javivelasco could move react-css-themr under the react-toolbox org, so we can upgrade that package, as it is a fundamental part to react-toolbox theming.

**Comment by that1matt** [comment]
@rubenmoya is there a way we can cut a new beta release with all the changes so far. As well as close some of the old PRs that have been resolved?

**Pull request merged**
