### PR TITLE
Add chip component

### PR DESCRIPTION
**Pull request by lucaas**
Adds a basic chip component implementing the [Chips specification](https://www.google.com/design/spec/components/chips.html#) to address issue #430.

Some things to consider:

* The delete icon is larger than in the reference images, but follows the spec sizes.
* I didn't add a explicit `onDelete` property, but simply rely on the standard `onClick`.
* Which approach would be more in line with the rest of the components, passing in `avatar` and `label` as props, or child components?
* I've replaced the rendering of autocomplete values with chips, but left it there as I wanted to keep this pull request small and not tackle the complete scope in #174.

Please let me know if there are anything more I should address.

### CODE REVIEW

**Comment by acornejo** [comment]
This is great Lucaas! I hope the maintainers take a look at this PR soon.

I have a few questions though, would the onClick allow a user of this component to distinguish between someone clicking the chip and someone clicking the delete button? Both events seem like could be of interest.

Also it would be nice if in addition to being able to specify a label (which is what most use cases want), one could instead pass children components to do custom labeling (for instance, to display user name where firstname is bold and lastname is not, etc..).

In any case, any version of this component seems like a great addition to react-toolbox! Thanks!

**Comment by javivelasco** [comment]
Hi! Thanks for this new component! As @acornejo pointed, I think it should be possible to give raw children but that's not a change that should take too long to do. Apart from that, I cloned the branch to check the changes and noticed it can be just a little tweaked to look even better.

I had an approach for the Chip in local that never updated so I change compare implementations a maybe fix this small pixel-level details. I'll do it during the day a release a new patch so you guys can start using it now!

**Comment by lucaas** [comment]
Thanks for the feedback!

I can take a stab at adding a separate `onDeleteClick` prop and moving `label` and `avatar` to children instead.

Styling it was a bit trickier than I expected, you are more than welcome to update it.

- [ ] Add `onDeleteClick` property
- [ ] Use children instead of special `label` and `avatar` props in Chip component.

**Comment by lucaas** [comment]
Done.

Please check that you agree with how I check if the component has an `Avatar` child. I am not sure if that is best practice, but need a way to control the padding of the chip and sizing of avatar if one is present.

On a related note, I am not entirely sure about the `deletable` prop either, would it better to rely on the presence of a `onDeleteClick` callback? Or should it be named something else to make it more intuitive, maybe `readonly` (with inverse behaviour)?

When I added the `onDeleteCallback`, I also removed the hover and active styles for the chip since I imagine that they wouldn't commonly be wanted.

**Comment by kagux** [comment]
great work @lucaas !
would it be possible to add animated or static gif of how it looks in PR?

**Comment by lucaas** [comment]
Thanks @kagux. I haven't added any animations, so a static image should be enough; Here are the autocomplete and chip examples from the spec page:

screen shot 2016-04-04 at 12 11 03

screen shot 2016-04-04 at 12 11 30

**Comment by lucaas** [comment]
After looking at the spec page again, I think I confused the size of the "remove area" and filled circle with the remove icon. It appears as it doesn't fill the whole area, and will probably look better as a smaller circle.

- [ ] Make remove icon smaller.

I also thought about if the use of `FontIcon` for the remove icon was appropriate, or if it would be better to use a more self-contained inline SVG to avoid having a dependency on the Material design icon font for something so trivial.

**Comment by acornejo** [comment]
+1 for your inline SVG idea. However, if that is something that will take you a while to do, I think its better to get *some* version of your PR merged and it can be polished later. Also from your screenshot it seems clear the delete icon is not vertically centered in the chip (its closer to the bottom than it is to the top), but again I think that is a problem we can live with for the first version of this component.

great work!

**Comment by lucaas** [comment]
I've pushed a new commit which replaces the FontIcon with an inline SVG and updates sizes to better match how it looks in Google's spec. 

screen shot 2016-04-05 at 10 52 51

**Comment by javivelasco** [comment]
Really beautiful @lucaas !! Congrats and thanks for the great work! 💃🏻

**Comment by aaj** [comment]
Not sure if I broke something, but I'm on 1.2.1 and my chips look like this:

image

**Comment by acornejo** [comment]
its definitely something wrong with your setup. I have an app running on 1.2.1 using chips and it looks just fine. Based on your screenshot even the font looks wrong, probably not importing your css correctly (i.e. incorrect webpack config).

I suggest you try to reproduce your problem with chips on this project https://github.com/react-toolbox/react-toolbox-example

**Comment by javivelasco** [comment]
Maube you are missing the commons.css imports or the Roboto font?

**Pull request merged**
