### PR TITLE
When the font-size (or $unit) is small, there's no difference between selected and unselected item

### PR DESCRIPTION
**Pull request by zalmoxisus**

### CODE REVIEW

**Comment by javivelasco** [comment]
May you add a screenshot or something to illustrate the problem and solution?
Thanks for the PR!

**Comment by zalmoxisus** [comment]
Surely, as you see in [the first screenshot](https://github.com/zalmoxisus/social-expert#social-expert) the selected item doesn't have a different font weight due to small font size, so we differentiate it by adding a background color.

**Comment by javivelasco** [comment]
Alright! I'd be very happy if you mention React Toolbox as well in the Readme!
It's a very nice project BTW, congrats!

**Comment by zalmoxisus** [comment]
@javivelasco, added. Thank you for the great tools!

**Comment by javivelasco** [comment]
Thank you for your mention and PR @zalmoxisus ! :)

**Comment by waxmihs2902** [comment]
good thing hapen to good people like you.. lets pag it forward! cheers! thanks tol all!

**Pull request merged**
