### PR TITLE
handle defaultValue to <Input />

### LINKED ISSUE #1175: Support defaultValue as a prop for Inputs
If I set `defaultValue` into an input, the label doesn't properly move to the desired position until I focus on the input.
Input bug

### PR DESCRIPTION
**Pull request by rubenmoya**
This fixes #1175. I don't know if it's the best way to handle it, so any feedback is appreciated :)

(I also refactored the `React.PropTypes` to `PropTypes`)

### CODE REVIEW

**Comment by javivelasco** [comment]
Can you fix conflics?!

**Comment by rubenmoya** [comment]
Done!

**Comment by javivelasco** [comment]
Thanks!

**Comment by NarasimhaReddyY** [comment]
@javivelasco when would i expect this on master?

**Pull request merged**
