### PR TITLE
Fix ripple overflowing outside the boundaries of list item

### LINKED ISSUE #1205: List ListItem Ripple effect Issue
The ripple effect moves outside the bounds of the element, I've copied the example straight from docs, this occurs only with List.

| Library            | Version        | 
|:-----|:-----|
| `react`      | `15.4.2`   | 
|`react-toolbox` |`^2.0.0-beta.6` |

Image

### PR DESCRIPTION
**Pull request by gustavohenke**
Fixes #1205 

Bug introduced as a typo in #1180

### CODE REVIEW

**Comment by olegstepura** [comment]
@javivelasco please merge this and release new build, ripple issue is annoying

**Comment by codeaid** [comment]
Not sure why but the issue persists after applying this change manually in my project. Are you sure it's a correct fix?

**Comment by gustavohenke** [comment]
Hi @codeaid, yes I'm sure. Perhaps you're applying the change incorrectly?

**Comment by gustavohenke** [comment]
If you setup my fork locally and start it, you'll be able to check this.

**Comment by javivelasco** [comment]
Sorry guys, I had a very busy week! Merged

**Pull request merged**
