### PR TITLE
Restrict dependencies to major versions only.

### PR DESCRIPTION
**Pull request by borela**
All dependencies are following semver, so we should assume that only bumps into major versions would break this project.

This pull request relax the dependencies a bit without allowing breaking changes.

### CODE REVIEW

**Comment by borela** [comment]
Fixes #979 and #970.

**Comment by kockok** [comment]
Hello, is the problem solved? 
I still have these warnings.
Or should I just ignore them?


> npm WARN react-toolbox@2.0.0-beta.8 requires a peer of react@^0.14 || ~15.4.0 but none was installed.
npm WARN react-toolbox@2.0.0-beta.8 requires a peer of react-addons-css-transition-group@^0.14.0 || ~15.4.0 but none was installed.
npm WARN react-toolbox@2.0.0-beta.8 requires a peer of react-dom@^0.14.0 || ~15.4.0 but none was installed.

**Comment by javivelasco** [comment]
They are peer dependencies so you need to add them manually to your project. It is assumed that if you use React Toolbox you'll have React installed :)

**Comment by chiester** [comment]
Is it the case that react-toolbox itself uses React 15.4.1, but requires projects that use it be on 15.4.0 or earlier?

**Comment by javivelasco** [comment]
Yeah, as stated in the `peerDependencies`. Anyway I think other versions would make it work but you will get a npm/yarn warning when installing

**Comment by kockok** [comment]
The warning dismissed after changing `^15.4` to `~15.4.0`. Haha

**Pull request merged**
