### PR TITLE
Added onMouseUp and onMouseLeave props to Icon Button

### PR DESCRIPTION
**Pull request by KerenChandran**
Added these prop types to make it similar to the Button.

### CODE REVIEW

**Comment by tungv** [comment]
+1

**Comment by tungv** [comment]
please merge this and publish to npm. many thanks!

**Comment by KerenChandran** [comment]
@tungv Hey I know you're in a rush to see this fix, but the owner of the repo usually merges on Thursday/Friday as he might be busy throughout the entire week.

**Comment by javivelasco** [comment]
Thanks @KerenChandran !! for both the PR and your response.
You're right, I have some accumulated PRs and issues and I want to answer and check everything during next weekend. Having a retreat with my company now so I can't release and review every PR. You will see a new release this weekend!!

**Comment by tungv** [comment]
+1
sorry for the rush. I really appreciate it.

**Comment by tungv** [comment]
@javivelasco, do we have any npm release with this fix anytime soon? This is a huge blocker for our project.

**Comment by javivelasco** [comment]
Sure. This afternoon, apologies

**Pull request merged**
