### PR TITLE
Typescript definitions validation

### PR DESCRIPTION
**Pull request by panjiesw**
This is a follow up attempt of the one described in #1118 .

- [x] Add typescript compiler and types dependencies.
- [x] Add task to package.json to validate definitions (without emitting the compiled result).
- [x] Add components spec written in typescript in `spec/ts` directory.

The third one is a going to be a while. I think it's necessary to write them so anyone contributing any ts definitions can try to use it there. But I'm open to any other suggestion of how to achieve the intention.

### CODE REVIEW

**Comment by javivelasco** [comment]
How is this going? What do you think about #935?

**Comment by panjiesw** [comment]
@javivelasco slow, unfortunately... :frowning_face: 

#935 is already implemented in `1.3.4` actually. The props and theme interfaces are all already exported in index.d.ts when I did the restructure.

**Comment by javivelasco** [comment]
Don't worry, take your time! I'm closing that one then

**Comment by Kikobeats** [comment]
IMHO would be better move this specific typescript rules in a separate and complementary package, like `react-toolbox-definitions`

**Comment by panjiesw** [comment]
@javivelasco do you still interested in this? Or should we separate the typescript stuff outside this repo as @Kikobeats said?

**Comment by panjiesw** [comment]
@javivelasco it's done now, it can be merged if you still have interest in this

**Comment by javivelasco** [comment]
Gotta check it out in more detail, patience! :)

**Comment by stereokai** [comment]
@panjiesw  @javivelasco when this is merged, would it be possible to use react-toolbox with typescript?

**Comment by panjiesw** [comment]
You can use `react-toolbox` with typescript just fine right now both in stable `1.3.4` and beta `2.0.0-beta.6`.

This PR is more of an enhancement for the development of `react-toolbox` and its typescript definitions, so that typescript users will have more pleasant experience when creating app with those wonderful tools (react-toolbox and typescript) :smile:

**Comment by stereokai** [comment]
I see. Thanks a lot :)

**Comment by seivan** [comment]
I second to add this directly to this repo so it just works out of the box instead of having to add dev-dependencies (@types/react-toolbox) 
I noticed there were test cases to test existing type definitions. Is there a way to setup a linter on the CI to ensure that future components also have typescript support?

**Pull request merged**
