### PR TITLE
Fix material design icons

### LINKED ISSUE #1320: material-design-icons Not works. Bad markup
Version: 2.0.0-beta.7

Icons looks like not working. Bad markup
```js
<Button icon='bookmark' label='Bookmark' raised primary />
```
Generates the folowing html code
```html
<button class="_2Agdx _221ic _2Agdx _2GH_L _1ZxqC _3tTAW" type="button" data-react-toolbox="button">
    <span data-react-toolbox="font-icon" aria-label="" class="material-icons _3aBSX">
        <span aria-hidden="true">bookmark</span>
    </span>
    <!-- react-text: 33 -->
    Bookmark
    <!-- /react-text -->
</button>
```
Should be
```html
<button class="_2Agdx _221ic _2Agdx _2GH_L _1ZxqC _3tTAW" type="button" data-react-toolbox="button">
    <span data-react-toolbox="font-icon" aria-hidden="true" class="material-icons _3aBSX">bookmark</span>
    <!-- react-text: 33 -->
    Bookmark
    <!-- /react-text -->
</button>
```
As described here the markup is different http://google.github.io/material-design-icons/#using-the-icons-in-html

### PR DESCRIPTION
**Pull request by FDiskas**
Fixes #1320

### CODE REVIEW

**Comment by FDiskas** [comment]
Before fix http://mechanic-rabbit-63688.netlify.com/ :smile:
After fix https://58c459eac4d9cc19b5c3a57e--mechanic-rabbit-63688.netlify.com/  :white_check_mark:

**Comment by FDiskas** [comment]
Any news?

**Comment by FDiskas** [comment]
:boar:

**Comment by javivelasco** [comment]
Sorry, I'm not having time at all during this week. Will try to release this during the next two days. Thanks for the fix :)

**Pull request merged**
