### PR TITLE
fix spec list link

### PR DESCRIPTION
**Pull request by ustccjw**
Maybe it's not the real man...

### CODE REVIEW

**Comment by soyjavi** [comment]
LOL

**Comment by ustccjw** [comment]
The origin link can not open. May be you could fix it.

**Comment by javivelasco** [comment]
:laughing:

**Comment by ustccjw** [comment]
@javivelasco https://pbs.twimg.com/profile_images/651611834131222528/rKYHs2bd_400x400.jpg is really disabled.:unamused:

**Comment by javivelasco** [comment]
It was @soyjavi avatar, changed now :dancer:

**Comment by soyjavi** [comment]
I will upload files to docs

**Pull request closed without merging**
