### PR TITLE
Add TypeScript definition file and typings entry to package.json

### LINKED ISSUE #199: Any chance of TypeScript definitions support?
It became very popular today, and may be already worth to create ones

### PR DESCRIPTION
**Pull request by hsrobflavorus**
As well as a blurb in README.md. This should resolve #199

### CODE REVIEW

**Comment by javivelasco** [comment]
Awesome! Thanks!!

**Comment by xogeny** [comment]
:+1:

**Comment by hsrobflavorus** [comment]
@xogeny Thanks for the initial definition layout!!! I couldn't have done this without it.

**Comment by alltom** [comment]
Do you happen to have a public project that uses react-toolbox with TypeScript that I could use as an example? I'm having trouble with the configuration.

**Comment by javivelasco** [comment]
If somebody has one, I think we should share the link in the Readme too!

**Comment by xogeny** [comment]
If I get some time, I might try to incorporate this into [my Typescript+React+Vada implementation of TodoMVC](https://github.com/xogeny/vada-todo).  All UI stuff is represented in this [single file](https://github.com/xogeny/vada-todo/blob/master/src/view.tsx).  Of course, I'd gladly accept a pull request for an alternate implementation from somebody else too.

**Comment by hsrobflavorus** [comment]
@alltom Please check out the updated definition file that was added in #293  

There were some problems (and possibly slight changes on the react-toolbox side) with the previous version, but the new one is merged in and should hopefully fix the issues you were having.

**Pull request merged**
