### PR TITLE
Change all colors to RGB values

### PR DESCRIPTION
**Pull request by EnzoMartin**
Implements proposed changes for #131

### CODE REVIEW

**Comment by EnzoMartin** [comment]
Also now removes all `unquote` calls

**Comment by soyjavi** [comment]
Hi @EnzoMartin .. can you send the PR only with the necessary push (not `merge` PR please)

**Comment by EnzoMartin** [comment]
Rebased correctly now, should be set to test it :+1:

**Comment by javivelasco** [comment]
Great!

**Pull request merged**
