### PR TITLE
Upgraded to support React 16

### PR DESCRIPTION
**Pull request by mattiasrunge**
Fixes https://github.com/react-toolbox/react-toolbox/issues/1694

Updated other dependencies as well

Updated enzyme required fixes to tests

Updated react-transition-group required small updates in Calendar and Clock components

### CODE REVIEW

**Comment by rubenmoya** [comment]
Hi! The upgrade to React 16 & Enzyme 3 is already merged in the [agnostic-typescript](https://github.com/react-toolbox/react-toolbox/tree/agnostic-typescript) branch which, hopefully,  will be merged to `dev` soon.

Do you mind opening a PR against that branch with the changes for react-transition-group? The `v2` (which comes from `dev` branch) is in `packages/react-toolbox`.

Thank you for your contribution! :D

**Comment by pablolmiranda** [comment]
Any change we have a react-toolbox 1.x compatible to React 16 before v2 is ready?

**Comment by mihiramin89** [comment]
any update on when this will be merged &  released?

**Comment by mattiasrunge** [comment]
@rubenmoya I took a look at that branch but it seems to depend on React 15 still at least from reading the package.json in packages/react-toolbox so it seems it was no easy fix. I could try to do it but I have not had the time unfortunatly, will take a more thorough look if I can find the time.

**Comment by Mythli** [comment]
I recently used your PR on react toolbox as we are using that to develop our next product.

However,

the issues that occured before applying your PR still remained.

React.findDOMNode somehow always returns null which results in all kinds of follow-up errors such as the ripple not working. 

I was able to fix that for the Menu using refs. 

Have you investigated that further?

**Comment by mattiasrunge** [comment]
@Mythli No I have not. Seems react-toolbox is not updated any longer, so I will not put any more effort into this unfortunately.

**Comment by Mythli** [comment]
For anybody interested, I asked that on SO and React.findDOMNode seems to be unreliable with fiber.

https://stackoverflow.com/questions/48062095/update-to-react-16-finddomnode-stops-working/48273014#48273014

**Comment by mlcohen** [comment]
@rubenmoya Is there a reason why @mattiasrunge's PR can't be merged into the `dev` branch and then published? Mattias's PR would at least allow people to move ahead with upgrading to react-toolbox v2 instead of waiting for the `agnostic-typescript` branch to be ready and merged, which at this point seems to have come to a complete standstill for a few months now.

**Comment by rubenmoya** [comment]
Closed in favor of https://github.com/react-toolbox/react-toolbox/pull/1814

**Pull request closed without merging**
